install:
  - sudo apt-get install python3-setuptools
  - git clone https://github.com/qmk/qmk_firmware.git && cd qmk_firmware
  - sudo ./util/qmk_install.sh
  - pushd .. && ln -s `pwd`/gergo-layout `pwd`/qmk_firmware/keyboards/gergo/sklarsa && popd

script:
  - make gergo:sklarsa
