language: python
python:
  - "3.7"
install:
  - git clone https://github.com/qmk/qmk_firmware.git && cd qmk_firmware
  - pip install --upgrade setuptools
  - sudo ./util/qmk_install.sh
  - pushd .. && ln -s `pwd`/gergo-layout `pwd`/qmk_firmware/keyboards/gergo/sklarsa && popd

script:
  - cd qmk_firmware && make gergo:sklarsa
